version: '3.8'

services:
  bakery-user-db:
    image: postgres:16.11-alpine
    container_name: bakery-user-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bakery-user-db
    ports:
      - "5432:5432"
    volumes:
      - bakery_user_db:/var/lib/postgresql/data

  bakery-eureka-service:
    image: nntan041299/bakery-eureka-service:0.0.1-SNAPSHOT
    container_name: bakery-eureka-service
    ports:
      - "8082:8082"
    environment:
      HOST_NAME: bakery-eureka-service
      SPRING_PROFILES_ACTIVE: prod

  bakery-user-service:
    image: nntan041299/bakery-user-service:0.0.1-SNAPSHOT
    container_name: bakery-user-service
    ports:
      - "8081:8081"
    depends_on:
      - bakery-user-db
      - bakery-eureka-service
    environment:
      HOST_NAME: bakery-user-service
      EUREKA_HOST: bakery-eureka-service
      EUREKA_PORT: 8082
      REGISTRY_FETCH_INTERVAL_SECONDS: 2
      INITIAL_INSTANCE_INFO_REPLICATION_INTERVAL_SECONDS: 2
      INSTANCE_INFO_REPLICATION_INTERVAL_SECONDS: 2
    env_file:
      - .user-service-env

  bakery-api-gateway:
    image: nntan041299/bakery-api-gateway:0.0.1-SNAPSHOT
    container_name: bakery-api-gateway
    ports:
      - "8083:8083"
    depends_on:
      - bakery-eureka-service
    environment:
      SPRING_PROFILES_ACTIVE: prod
      HOST_NAME: bakery-api-gateway
      EUREKA_HOST: bakery-eureka-service
      EUREKA_PORT: 8082
      REGISTRY_FETCH_INTERVAL_SECONDS: 2
      INITIAL_INSTANCE_INFO_REPLICATION_INTERVAL_SECONDS: 2
      INSTANCE_INFO_REPLICATION_INTERVAL_SECONDS: 2

volumes:
  bakery_user_db:
